apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name }}-models
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    # volume can be mounted as read-write by a single node
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
