apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "squid.fullname" . }}-conf
  labels:
    app: {{ template "squid.name" . }}
    chart: {{ template "squid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  squid.conf: |
{{ .Values.config | indent 4 }}