kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.data.claimName }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with .Values.persistence.data.annotations }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: {{ .Values.persistence.data.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.temp.claimName }}
  annotations:
    {{- with .Values.persistence.data.annotations }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: {{ .Values.persistence.temp.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.temp.size }}
